from langchain_core.language_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser


class SimpleAgent():
    """
    A simple agent that utilizes a language model to process and respond to queries.

    This agent is initialized with a language model (LLM) and a system prompt. The `run` method 
    takes a user query, processes it through the language model using the predefined system prompt, 
    and returns the generated response.

    Attributes:
        llm (BaseChatModel): The language model used for generating responses.
        system_prompt (str): The initial prompt or instruction that guides the language model's behavior.

    Methods:
        run(query: str) -> str:
            Processes the input query through the language model and returns the generated response. 
    """
    def __init__(
            self, 
            llm: BaseChatModel, 
            system_prompt: str
        ) -> None:
        """
        Initializes the SimpleAgent with a language model and a system prompt.

        Args:
            llm (BaseChatModel): The language model to be used for generating responses.
            system_prompt (str): The initial prompt or instruction that guides the language model's behavior. 
        """
        self.llm = llm
        self.system_prompt = system_prompt

    def run(self, query: str) -> str:
        """
        Processes the input query through the language model and returns the generated response.

        Args:
            query (str): The user input or query to be processed.

        Returns:
            str: The response generated by the language model based on the system prompt and the input query. 
        """
        chain = self.system_prompt | self.llm | StrOutputParser()

        return chain.invoke(query)
    
if __name__=="__main__": #pragma: no-cover

    from chatbot_prompt.simple_agent_prompt import system_prompt
    from langchain_groq import ChatGroq

    llm = ChatGroq(
        model="llama3-70b-8192", 
        temperature = 0.5, 
        api_key = "your-api-key"  
    )

    simple_agent = SimpleAgent(
        llm           = llm, 
        system_prompt = system_prompt   
    )

    print("Olá! Eu sou a Lily, prazer. O que deseja conversar, caro(a) morceguinho(a) ?")
    while True: 

        user_input = input("Palavras soltas: ")
        if user_input.lower() in ["sair", "exit"]: 
            print("Até mais! Trombamos por aí depois...")
            break
        try:
            response = simple_agent.run(query=user_input)
            print(f"Lily: {response}")
        except Exception as e: 
            print(f"Erro ao processar a mensagem {e}")
